# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts.xdc

# Block Designs: bd/mts/mts.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts || ORIG_REF_NAME==mts} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_broadcaster_0_0/mts_axis_broadcaster_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_broadcaster_0_0 || ORIG_REF_NAME==mts_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_BUFG_PL_CLK_0/mts_BUFG_PL_CLK_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_BUFG_PL_CLK_0 || ORIG_REF_NAME==mts_BUFG_PL_CLK_0} -quiet] -quiet

# IP: bd/mts/ip/mts_MTSclkwiz_0/mts_MTSclkwiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_MTSclkwiz_0 || ORIG_REF_NAME==mts_MTSclkwiz_0} -quiet] -quiet

# IP: bd/mts/ip/mts_PSreset_control_0/mts_PSreset_control_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_PSreset_control_0 || ORIG_REF_NAME==mts_PSreset_control_0} -quiet] -quiet

# IP: bd/mts/ip/mts_RFegressReset_0/mts_RFegressReset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_RFegressReset_0 || ORIG_REF_NAME==mts_RFegressReset_0} -quiet] -quiet

# IP: bd/mts/ip/mts_RFingressReset_0/mts_RFingressReset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_RFingressReset_0 || ORIG_REF_NAME==mts_RFingressReset_0} -quiet] -quiet

# IP: bd/mts/ip/mts_synchronizeSYSREF_0/mts_synchronizeSYSREF_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_synchronizeSYSREF_0 || ORIG_REF_NAME==mts_synchronizeSYSREF_0} -quiet] -quiet

# IP: bd/mts/ip/mts_xbar_0/mts_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xbar_0 || ORIG_REF_NAME==mts_xbar_0} -quiet] -quiet

# IP: bd/mts/ip/mts_auto_pc_0/mts_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_auto_pc_0 || ORIG_REF_NAME==mts_auto_pc_0} -quiet] -quiet

# IP: bd/mts/ip/mts_control_interconnect_0/mts_control_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_control_interconnect_0 || ORIG_REF_NAME==mts_control_interconnect_0} -quiet] -quiet

# IP: bd/mts/ip/mts_ddr4_0_0/mts_ddr4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ddr4_0_0 || ORIG_REF_NAME==mts_ddr4_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_dma_adc_0/mts_axi_dma_adc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_dma_adc_0 || ORIG_REF_NAME==mts_axi_dma_adc_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_data_fifo_adc_0/mts_axis_data_fifo_adc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_data_fifo_adc_0 || ORIG_REF_NAME==mts_axis_data_fifo_adc_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_dwidth_converter_0_0/mts_axis_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_dwidth_converter_0_0 || ORIG_REF_NAME==mts_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_rst_ddr4_0_333M_0/mts_rst_ddr4_0_333M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_rst_ddr4_0_333M_0 || ORIG_REF_NAME==mts_rst_ddr4_0_333M_0} -quiet] -quiet

# IP: bd/mts/ip/mts_xlconstant_0_0/mts_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xlconstant_0_0 || ORIG_REF_NAME==mts_xlconstant_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_xlconstant_1_0/mts_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xlconstant_1_0 || ORIG_REF_NAME==mts_xlconstant_1_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_gpio_bram_adc_0/mts_axi_gpio_bram_adc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_gpio_bram_adc_0 || ORIG_REF_NAME==mts_axi_gpio_bram_adc_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_gpio_dac_0/mts_axi_gpio_dac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_gpio_dac_0 || ORIG_REF_NAME==mts_axi_gpio_dac_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_gpio_fifoflush_0/mts_axi_gpio_fifoflush_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_gpio_fifoflush_0 || ORIG_REF_NAME==mts_axi_gpio_fifoflush_0} -quiet] -quiet

# IP: bd/mts/ip/mts_xpm_cdc_gen_0_0/mts_xpm_cdc_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xpm_cdc_gen_0_0 || ORIG_REF_NAME==mts_xpm_cdc_gen_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_ADCRAMcapture_0_0/mts_ADCRAMcapture_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ADCRAMcapture_0_0 || ORIG_REF_NAME==mts_ADCRAMcapture_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_bram_ctrl_0_0/mts_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mts_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_clock_converter_0_0/mts_axis_clock_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_clock_converter_0_0 || ORIG_REF_NAME==mts_axis_clock_converter_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_dwidth_converter_0_1/mts_axis_dwidth_converter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_dwidth_converter_0_1 || ORIG_REF_NAME==mts_axis_dwidth_converter_0_1} -quiet] -quiet

# IP: bd/mts/ip/mts_blk_mem_gen_0_0/mts_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_blk_mem_gen_0_0 || ORIG_REF_NAME==mts_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_ADCRAMcapture_0_1/mts_ADCRAMcapture_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ADCRAMcapture_0_1 || ORIG_REF_NAME==mts_ADCRAMcapture_0_1} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_bram_ctrl_0_1/mts_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_bram_ctrl_0_1 || ORIG_REF_NAME==mts_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_clock_converter_0_1/mts_axis_clock_converter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_clock_converter_0_1 || ORIG_REF_NAME==mts_axis_clock_converter_0_1} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_dwidth_converter_0_2/mts_axis_dwidth_converter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_dwidth_converter_0_2 || ORIG_REF_NAME==mts_axis_dwidth_converter_0_2} -quiet] -quiet

# IP: bd/mts/ip/mts_blk_mem_gen_0_1/mts_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_blk_mem_gen_0_1 || ORIG_REF_NAME==mts_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/mts/ip/mts_ADCRAMcapture_0_2/mts_ADCRAMcapture_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ADCRAMcapture_0_2 || ORIG_REF_NAME==mts_ADCRAMcapture_0_2} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_bram_ctrl_0_2/mts_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_bram_ctrl_0_2 || ORIG_REF_NAME==mts_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_clock_converter_0_2/mts_axis_clock_converter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_clock_converter_0_2 || ORIG_REF_NAME==mts_axis_clock_converter_0_2} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_dwidth_converter_0_3/mts_axis_dwidth_converter_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_dwidth_converter_0_3 || ORIG_REF_NAME==mts_axis_dwidth_converter_0_3} -quiet] -quiet

# IP: bd/mts/ip/mts_blk_mem_gen_0_2/mts_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_blk_mem_gen_0_2 || ORIG_REF_NAME==mts_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/mts/ip/mts_ADCRAMcapture_0_3/mts_ADCRAMcapture_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ADCRAMcapture_0_3 || ORIG_REF_NAME==mts_ADCRAMcapture_0_3} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_bram_ctrl_0_3/mts_axi_bram_ctrl_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_bram_ctrl_0_3 || ORIG_REF_NAME==mts_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_clock_converter_0_3/mts_axis_clock_converter_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_clock_converter_0_3 || ORIG_REF_NAME==mts_axis_clock_converter_0_3} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_dwidth_converter_0_4/mts_axis_dwidth_converter_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_dwidth_converter_0_4 || ORIG_REF_NAME==mts_axis_dwidth_converter_0_4} -quiet] -quiet

# IP: bd/mts/ip/mts_blk_mem_gen_0_3/mts_blk_mem_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_blk_mem_gen_0_3 || ORIG_REF_NAME==mts_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/mts/ip/mts_DACRAMstreamer_0_0/mts_DACRAMstreamer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_DACRAMstreamer_0_0 || ORIG_REF_NAME==mts_DACRAMstreamer_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_bram_ctrl_0_4/mts_axi_bram_ctrl_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_bram_ctrl_0_4 || ORIG_REF_NAME==mts_axi_bram_ctrl_0_4} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_clock_converter_0_4/mts_axis_clock_converter_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_clock_converter_0_4 || ORIG_REF_NAME==mts_axis_clock_converter_0_4} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_dwidth_converter_0_5/mts_axis_dwidth_converter_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_dwidth_converter_0_5 || ORIG_REF_NAME==mts_axis_dwidth_converter_0_5} -quiet] -quiet

# IP: bd/mts/ip/mts_axis_register_slice_0_0/mts_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axis_register_slice_0_0 || ORIG_REF_NAME==mts_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_blk_mem_gen_0_4/mts_blk_mem_gen_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_blk_mem_gen_0_4 || ORIG_REF_NAME==mts_blk_mem_gen_0_4} -quiet] -quiet

# IP: bd/mts/ip/mts_xlconstant_0_1/mts_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xlconstant_0_1 || ORIG_REF_NAME==mts_xlconstant_0_1} -quiet] -quiet

# IP: bd/mts/ip/mts_xbar_1/mts_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xbar_1 || ORIG_REF_NAME==mts_xbar_1} -quiet] -quiet

# IP: bd/mts/ip/mts_auto_us_0/mts_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_auto_us_0 || ORIG_REF_NAME==mts_auto_us_0} -quiet] -quiet

# IP: bd/mts/ip/mts_auto_rs_0/mts_auto_rs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_auto_rs_0 || ORIG_REF_NAME==mts_auto_rs_0} -quiet] -quiet

# IP: bd/mts/ip/mts_auto_rs_w_0/mts_auto_rs_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_auto_rs_w_0 || ORIG_REF_NAME==mts_auto_rs_w_0} -quiet] -quiet

# IP: bd/mts/ip/mts_internalRAM_interconnect_0/mts_internalRAM_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_internalRAM_interconnect_0 || ORIG_REF_NAME==mts_internalRAM_interconnect_0} -quiet] -quiet

# IP: bd/mts/ip/mts_smartconnect_0_0/mts_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_smartconnect_0_0 || ORIG_REF_NAME==mts_smartconnect_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_system_ila_0_0/mts_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_system_ila_0_0 || ORIG_REF_NAME==mts_system_ila_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_system_management_wiz_0_0/mts_system_management_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_system_management_wiz_0_0 || ORIG_REF_NAME==mts_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_usp_rf_data_converter_1_0/mts_usp_rf_data_converter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_usp_rf_data_converter_1_0 || ORIG_REF_NAME==mts_usp_rf_data_converter_1_0} -quiet] -quiet

# IP: bd/mts/ip/mts_xlconcat_0_0/mts_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xlconcat_0_0 || ORIG_REF_NAME==mts_xlconcat_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_zynq_ultra_ps_e_0_0/mts_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mts_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/mts_ooc.xdc
