# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.srcs/sources_1/bd/mts/ip/mts_auto_rs_w_0/mts_auto_rs_w_0.xci
# IP: The module: 'mts_auto_rs_w_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_auto_rs_w_0/mts_auto_rs_w_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_auto_rs_w_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_auto_rs_w_0/mts_auto_rs_w_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_auto_rs_w_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.srcs/sources_1/bd/mts/ip/mts_auto_rs_w_0/mts_auto_rs_w_0.xci
# IP: The module: 'mts_auto_rs_w_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_auto_rs_w_0/mts_auto_rs_w_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_auto_rs_w_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_auto_rs_w_0/mts_auto_rs_w_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_auto_rs_w_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
