# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.srcs/sources_1/bd/mts/ip/mts_ddr4_0_0/mts_ddr4_0_0.xci
# IP: The module: 'mts_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_1/mts_ddr4_0_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ddr4_0_0_phy || ORIG_REF_NAME==mts_ddr4_0_0_phy} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_0/mts_ddr4_0_0_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==mts_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/bd_787f.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f || ORIG_REF_NAME==bd_787f} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_0/bd_787f_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_microblaze_I_0 || ORIG_REF_NAME==bd_787f_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_1/bd_787f_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_rst_0_0 || ORIG_REF_NAME==bd_787f_rst_0_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_2/bd_787f_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_ilmb_0 || ORIG_REF_NAME==bd_787f_ilmb_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_3/bd_787f_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_dlmb_0 || ORIG_REF_NAME==bd_787f_dlmb_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_4/bd_787f_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_787f_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_5/bd_787f_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_787f_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_6/bd_787f_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_lmb_bram_I_0 || ORIG_REF_NAME==bd_787f_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_7/bd_787f_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_787f_second_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_8/bd_787f_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_787f_second_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_9/bd_787f_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_787f_second_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_10/bd_787f_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_iomodule_0_0 || ORIG_REF_NAME==bd_787f_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_1/par/mts_ddr4_0_0_phy_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_0/bd_787f_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_microblaze_I_0 || ORIG_REF_NAME==bd_787f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_0/bd_787f_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_1/bd_787f_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_rst_0_0 || ORIG_REF_NAME==bd_787f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_1/bd_787f_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_rst_0_0 || ORIG_REF_NAME==bd_787f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_2/bd_787f_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_ilmb_0 || ORIG_REF_NAME==bd_787f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_3/bd_787f_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_dlmb_0 || ORIG_REF_NAME==bd_787f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_6/bd_787f_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_9/bd_787f_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_10/bd_787f_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_iomodule_0_0 || ORIG_REF_NAME==bd_787f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/bd_787f_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_0/mts_ddr4_0_0_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mts_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==mts_ddr4_0_0_microblaze_mcs} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_0/mts_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/mts_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/par/mts_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.srcs/sources_1/bd/mts/ip/mts_ddr4_0_0/mts_ddr4_0_0.xci
# IP: The module: 'mts_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_1/mts_ddr4_0_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ddr4_0_0_phy || ORIG_REF_NAME==mts_ddr4_0_0_phy} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_0/mts_ddr4_0_0_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==mts_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/bd_787f.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f || ORIG_REF_NAME==bd_787f} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_0/bd_787f_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_microblaze_I_0 || ORIG_REF_NAME==bd_787f_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_1/bd_787f_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_rst_0_0 || ORIG_REF_NAME==bd_787f_rst_0_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_2/bd_787f_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_ilmb_0 || ORIG_REF_NAME==bd_787f_ilmb_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_3/bd_787f_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_dlmb_0 || ORIG_REF_NAME==bd_787f_dlmb_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_4/bd_787f_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_787f_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_5/bd_787f_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_787f_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_6/bd_787f_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_lmb_bram_I_0 || ORIG_REF_NAME==bd_787f_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_7/bd_787f_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_787f_second_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_8/bd_787f_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_787f_second_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_9/bd_787f_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_787f_second_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_10/bd_787f_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_787f_iomodule_0_0 || ORIG_REF_NAME==bd_787f_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_1/par/mts_ddr4_0_0_phy_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_0/bd_787f_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_microblaze_I_0 || ORIG_REF_NAME==bd_787f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_0/bd_787f_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_1/bd_787f_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_rst_0_0 || ORIG_REF_NAME==bd_787f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_1/bd_787f_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_rst_0_0 || ORIG_REF_NAME==bd_787f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_2/bd_787f_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_ilmb_0 || ORIG_REF_NAME==bd_787f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_3/bd_787f_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_dlmb_0 || ORIG_REF_NAME==bd_787f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_6/bd_787f_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_9/bd_787f_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/ip/ip_10/bd_787f_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_787f_iomodule_0_0 || ORIG_REF_NAME==bd_787f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/bd_0/bd_787f_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_0/mts_ddr4_0_0_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mts_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==mts_ddr4_0_0_microblaze_mcs} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/ip_0/mts_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/mts_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/joebe/Documents/RFSoC/RFSoC-MTS-main_ORIGINAL/RFSoC-MTS-main/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_ddr4_0_0/par/mts_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
